create or replace view VIEW_CRIME_BY_TYPE(
	AREA_NAME,
	CRIME_TYPE_GROUP,
	TOTAL_CRIMES
) as
SELECT 
  AREA_NAME, 
  CRIME_TYPE_GROUP,
  COUNT() AS total_crimes
FROM CRIME_DATA
GROUP BY AREA_NAME, CRIME_TYPE_GROUP
ORDER BY total_crimes DESC;