create or replace view VIEW_SEVERITY_TIMELINE(
	YEAR,
	MONTH,
	CRIME_SEVERITY,
	CRIME_COUNT
) as
SELECT 
  YEAR,
  MONTH,
  CRIME_SEVERITY,
  COUNT(*) AS crime_count
FROM CRIME_DATA
GROUP BY YEAR, MONTH, CRIME_SEVERITY
ORDER BY YEAR, MONTH;