create or replace view VIEW_CRIME_TRENDS(
	YEAR,
	MONTH,
	TIME_SLOT,
	CRIME_COUNT
) as
SELECT 
  YEAR,
  MONTH,
  TIME_SLOT,
  COUNT(*) AS crime_count
FROM CRIME_DATA
GROUP BY YEAR, MONTH, TIME_SLOT
ORDER BY YEAR, MONTH;